M48
; DRILL file {KiCad (6.0.5-0)} date Sunday, July 10, 2022 at 06:26:12 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-10T18:26:12-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X107.95Y-20.32
X107.95Y-167.573
X135.89Y-20.32
X135.89Y-167.573
T0
M30
