M48
; DRILL file {KiCad (6.0.5-0)} date Tuesday, August 16, 2022 at 12:13:15 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-16T12:13:15-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X33.02Y-177.8
X34.29Y-46.355
X66.04Y-177.8
X66.675Y-46.355
T0
M30
